config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  root to: 'controller#action'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy

    validates :name, :address, :category, presence: true

    validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, :content, presence: true

  validates :rating, numericality: { only_integer: true }, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show]

  # GET "restaurants"
  def index
    @restaurants = Restaurant.all
  end

  # GET "restaurants/new"
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # GET "restaurants/38"
  def show
    @review = Review.new
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:id, :name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # GET "restaurants/38/reviews/new"
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  # POST "restaurants/38/reviews"
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save # No guarantee it will save!
      # Happy path :)
      # Don't redirect if save went wrong
      redirect_to @restaurant
    else
      # Sad path :(
      render "new"
    end
  end

  private

  def review_params
    params.require(:review).permit(:id, :content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- NAVBAR -->
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
        <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", restaurants_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add a restaurant", new_restaurant_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/brizlelem", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
create.html.erb

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
        <li> <%= link_to restaurant.name, restaurant_path(restaurant) %> •
          <% if restaurant.reviews.count > 0 %>
            <% sum = restaurant.reviews.map(&:rating).sum %>
            (<%= average = sum.fdiv(restaurant.reviews.count) %>)
          <% else %>
            No rating yet
          <% end %>
         </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @restaurant.phone_number %>
</p>

<p>
  <strong>Rating:</strong>
  <% if @restaurant.reviews.count > 0 %>
            <% sum = @restaurant.reviews.map(&:rating).sum %>
            (<%= average = sum.fdiv(@restaurant.reviews.count).round(1) %>)
          <% else %>
            No rating yet
          <% end %>
</p>

<div>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li>
        <%= review.content %> (<%= review.rating %>)
      </li>
    <% end %>
  </ul>
</div>

<div>
  <h1>Add a review</h1>


 <!-- POST   /restaurants/:restaurant_id/reviews -->
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content %>
  <%= f.collection_radio_buttons :rating, [[1, '1'] ,[2, '2'],[3, '3'],[4, '4'],[5, '5']], :first, :last, include_hidden: true %>
  <br>
  <br>
  <%= f.submit class: "btn btn-secondary" %>
<% end %>
</div>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>Add review to <%= @restaurant.name %> </h1>


 <!-- POST   /restaurants/:restaurant_id/reviews -->
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content %>
  <%= f.collection_radio_buttons :rating, [[1, '1'] ,[2, '2'],[3, '3'],[4, '4'],[5, '5']], :first, :last, include_hidden: true %>
  <br>
  <br>
  <%= f.submit class: "btn btn-secondary" %>
<% end %>